name: Expo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v2

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3

      - name: ðŸ“¦ Install dependencies
        run: expo install 

      - name: âœ… Lint code
        run: expo lint --max-warnings=0

      - name: ðŸ§ª Test code
        run: expo start

      - name: ðŸ‘· Build code
        run: expo clean && expo build

      - name: ðŸ•µï¸ Validate build
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol build/ | wc -l)" -gt "0" ]; then
            echo "âš ï¸ Build is outdated"
            echo "    > run 'expo clean', 'expo build', and commit changes"
            git diff
            exit 1
          fi
      
      - name: ðŸ—‚ Upload build
        uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: build
          path: build/